# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e9ae4787744513d5e12c03cb9dd89022971893134a2e22fb18a8eaff6ae188d4cf8cb6e1ecb5f5487474c90240c43db4b257ae86118b5762d93a054893b36ac

test:
  secret_key_base: edaeb939931cc26e9a855019a08cdb06300d951f804d70259b31f69923a1627c6a8cc0831547ccd9915561e97dd7c1025153eae01d56f5bd817002d085c4deba 
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
